/* Including needed modules to compile this module/procedure */
#include "Cpu.h"
#include "Events.h"
#include "Pins1.h"
#include "ADC1.h"
#include "WAIT1.h"
#include "CsIO1.h"
#include "IO1.h"
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "PDD_Includes.h"
#include "fsl_device_registers.h"
#include "fsl_debug_console.h"
#include <stdint.h>

/* User includes (#include below this line is not maintained by Processor Expert) */

/*lint -save  -e970 Disable MISRA rule (6.3) checking. */

#define BUFFER_SIZE 2

int joystickFB, joystickLR;

uint8_t tx_buf[BUFFER_SIZE];

void initADC(void);
int readJoystick(uint8_t channelGroup, uint8_t channel);

int main(void)
/*lint -restore Enable MISRA rule (6.3) checking. */
{
    /* Processor Expert internal initialization. DON'T REMOVE THIS CODE!!! */
    PE_low_level_init();
    /* End of Processor Expert internal initialization. */

    /* Initialize debug console */
    BOARD_InitDebugConsole();

    /* Initialize ADC */
    initADC();

    /* Main loop */
    for(;;) {
        joystickFB = readJoystick(0, 12); // Read from PTB2 (ADC0_SE12)
        joystickLR = readJoystick(0, 13); // Read from PTB3 (ADC0_SE13)

        PRINTF("X: %d, Y: %d\r\n", joystickFB, joystickLR);

        WAIT1_Waitms(100); // Delay to avoid flooding the output
    }

    /*** Don't write any code past this line, or it will be deleted during code generation. ***/
    for(;;){}
}

/* Function to initialize ADC using Processor Expert settings */
void initADC(void) {
    // ADC initialization code should be generated by Processor Expert
    // and called by PE_low_level_init()
}

/* Function to read joystick value from specified ADC channel */
int readJoystick(uint8_t channelGroup, uint8_t channel) {
    ADC1_Measure(TRUE); // Start conversion
    while (!ADC1_GetValue16(&channelGroup, &channel)); // Wait for conversion to complete
    return ADC1_GetValue16(); // Return the ADC value
}
